
global: {}

service-account:
  name: artifactory-artifactory
  create: false
  sccs: ["anyuid", "privileged"]

config-service-account:
  name: artifactory-config
  roles:
  - apiGroups:
    - ''
    resources:
    - secrets
    - configmaps
    verbs:
    - "*"

artifactory:
  nameOverride: artifactory
  artifactory:
    image:
      repository: docker.bintray.io/jfrog/artifactory-oss
    adminAccess:
      password: admin
    persistence:
      enabled: true
      storageClassName: ''
      size: 5Gi
    uid: 0
  ingress:
    enabled: false
  postgresql:
    enabled: false
  nginx:
    enabled: false
  serviceAccount:
    create: true
    name: artifactory-artifactory

ocp-route:
  nameOverride: artifactory
  targetPort: router
  app: artifactory
  serviceName: artifactory-artifactory
  termination: edge
  insecurePolicy: Redirect

setup-job:
  name: artifactory
  serviceAccountName: artifactory-config
  command: setup-artifactory
  secret:
    name: artifactory-access
    key: ARTIFACTORY_URL

tool-config:
  name: Artifactory
  url: 'https://artifactory-tools.<Cluster-Domain>'
  privateUrl: 'http://artifactory-artifactory.tools:8082'
  username: admin
  password: password
  otherSecret:
    ENCRYPT_PASSWORD: ''
    ADMIN_USER: admin-access
    ADMIN_ACCESS_PASSWORD: admin
  applicationMenu: true
