apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ibm-test-pipeline-for-dev-env
  annotations:
    app.openshift.io/runtime: test
spec:
  params:
    - name: git-url
      description: The url for the queuemanager git repository
    - name: git-revision
      description: The git revision (branch, tag, or sha) that should be built
      default: master
    - name: environment
      description: Next environment to be promoted
      default: staging
    - name: argoAppName
      description: Name of the application deployed by argocd in dev namespace (ibm-mq-dev-instance or mq-quarkus-app-dev)
  tasks:
    - name: setup
      taskRef:
        name: ibm-setup-v2-5-0
      params:
        - name: git-url
          value: $(params.git-url)
        - name: git-revision
          value: $(params.git-revision)
    - name: img-info
      taskRef:
        name: ibm-img-info-extract
      runAfter:
        - setup
      params:
        - name: git-url
          value: "$(tasks.setup.results.git-url)"
        - name: git-revision
          value: "$(tasks.setup.results.git-revision)"
        - name: source-dir
          value: "$(tasks.setup.results.source-dir)"
        - name: image-from
          value: "$(tasks.setup.results.image-url)"
        - name: image-to
          value: "$(tasks.setup.results.image-release)"
    - name: dev-instance-tests
      taskRef:
        name: ibm-argo-tests
      runAfter:
        - img-info
      params:
        - name: image-url
          value: "$(tasks.img-info.results.image-url)"
        - name: argoAppName
          value: "$(params.argoAppName)"
    - name: promote-changes-to-queuemanager
      taskRef:
        name: ibm-update-image
      runAfter:
        - dev-instance-tests
      params:
        - name: git-url
          value: "$(tasks.setup.results.git-url)"
        - name: git-branch
          value: "$(params.environment)"
        - name: image-url
          value: "$(tasks.dev-instance-tests.results.image-url)"
