global: {}

ibm-catalogs:
  catalogs:
    commonservices:
      name: opencloud-operators
      catalog:
        displayName: IBMCS Operators
        publisher: IBM
        sourceType: grpc
        image: docker.io/ibmcom/ibm-common-service-catalog:latest
        updateStrategy:
          registryPoll:
            interval: 45m

    ibmoperators:
      name: ibm-operator-catalog
      catalog:
        displayName: "IBM Operator Catalog"
        publisher: IBM
        sourceType: grpc
        image: docker.io/ibmcom/ibm-operator-catalog
        updateStrategy:
          registryPoll:
            interval: 45m